void beq(const Label &label);
void beq(int64_t label);
void bne(const Label &label);
void bne(int64_t label);
void bcs(const Label &label);
void bcs(int64_t label);
void bcc(const Label &label);
void bcc(int64_t label);
void bmi(const Label &label);
void bmi(int64_t label);
void bpl(const Label &label);
void bpl(int64_t label);
void bvs(const Label &label);
void bvs(int64_t label);
void bvc(const Label &label);
void bvc(int64_t label);
void bhi(const Label &label);
void bhi(int64_t label);
void bls(const Label &label);
void bls(int64_t label);
void bge(const Label &label);
void bge(int64_t label);
void blt(const Label &label);
void blt(int64_t label);
void bgt(const Label &label);
void bgt(int64_t label);
void ble(const Label &label);
void ble(int64_t label);
void b_none(const Label &label);
void b_none(int64_t label);
void b_any(const Label &label);
void b_any(int64_t label);
void b_nlast(const Label &label);
void b_nlast(int64_t label);
void b_last(const Label &label);
void b_last(int64_t label);
void b_first(const Label &label);
void b_first(int64_t label);
void b_nfrst(const Label &label);
void b_nfrst(int64_t label);
void b_pmore(const Label &label);
void b_pmore(int64_t label);
void b_plast(const Label &label);
void b_plast(int64_t label);
void b_tcont(const Label &label);
void b_tcont(int64_t label);
void b_tstop(const Label &label);
void b_tstop(int64_t label);
